### ISSUE TITLE
Modbus

### ISSUE THREAD

**Issue by samuck1** [persandstrom/.homeassistant#1]
You have a USB modbus. Does your Hassio run in Blackberry? What devices do you use to connect modbus in Blackberry? Thank you

**Comment by persandstrom** [comment]
Hi. 

I use https://www.dx.com/p/usb-to-rs485-adapter-black-green-296620#.W-Z3fKjMB-F

And connect it to a raspberry

**Comment by samuck1** [comment]
Thank you very much. Do you need instal any driver after?  do you Connect the bus modbus direct to slaves devices , or do you need a master device?

**Comment by persandstrom** [comment]
No, I don't think any driver is needed. You can connect it directly to a slave device.

**Comment by samuck1** [comment]
Thank you very much . I am going to try. Yoi are very friendly

**Comment by persandstrom** [comment]
Good luck!
